version: '3'

services:

  apache:
    build: ./php-apache
    volumes:
      - ./src:/var/www/apache-server/html
      - ./apache-conf/httpd.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/apache-server/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  mysql:
    image: mysql
    hostname: MYSQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      HOSTNAME: MYSQL
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "dbdata:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 10

volumes:
  dbdata:
